# https://taskfile.dev

version: "3"

env:
  LOGSTYLE: console

vars:
  CONTAINER_REGISTRY: docker.io
  REPOSITORY: kevinzehnder
  IMAGE_NAME: phil
  IMAGE_TAG:
    sh: git describe --tags 2>/dev/null || echo develop
    
  GO_OS: linux # Default OS
  GO_ARCH: amd64 # Default architecture
  APP_NAME: phil # Application name
  ENTRYPOINT: cmd/main/main.go
  CONTAINER_NAME: phil_container
  LOCAL_PORT: 3000
  CONTAINER_PORT: 9000
  
tasks:
  run:
    desc: run main.go
    cmds:
      - go run {{.ENTRYPOINT}}

  build:
    internal: true
    vars:
      GO_OS: "{{ .GO_OS }}"
      GO_ARCH: "{{ .GO_ARCH }}"
    cmds:
      - GOOS={{ .GO_OS }} GOARCH={{ .GO_ARCH }} go build -o build/{{ .APP_NAME }}_{{ .GO_OS }}_{{ .GO_ARCH }} {{.ENTRYPOINT}}

  test:
    desc: run tests
    cmds:
      - gotest -v ./...
      
  container:
    deps: [image]
    desc: run in container
    cmds:
      - docker run -it --rm --name {{.CONTAINER_NAME}} -p {{.LOCAL_PORT}}:{{.CONTAINER_PORT}} -t {{.CONTAINER_REGISTRY}}/{{.REPOSITORY}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}
      
  image:
    desc: build container image
    cmds:
      - docker build -t {{.CONTAINER_REGISTRY}}/{{.REPOSITORY}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}} .
      
  push:
    desc: build container image
    cmds:
      - docker push {{.CONTAINER_REGISTRY}}/{{.REPOSITORY}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}

  swag:
    desc: create swagger docs
    cmds:
      - swag init --parseInternal -g {{.ENTRYPOINT}}

  air:
    desc: run air
    cmds:
      - air

  airup:
    silent: true
    desc: reload task for air
    cmds:
      - task swag
      - go build -o ./tmp/main {{.ENTRYPOINT}}
